In [1]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv('inputs/clean_data.csv')
data = data.drop(columns=['Unnamed: 0'], axis=1)
data.head()

,Loan Status,Current Loan Amount,Credit Score,Years in current job,Annual Income,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens,Loan_status_home_ownership,purpose_term
0,0,12232,728.0,0.0,46643.0,777.39,18.0,10.0,12,0,6762,7946.0,0.0,0.0,0.716932,0.743981
1,0,25014,733.0,10.0,81099.0,892.09,26.7,51.0,14,0,35706,77961.0,0.0,0.0,0.769393,0.743981
2,0,16117,724.0,9.0,60438.0,1244.02,16.7,32.0,11,1,11275,14815.0,1.0,0.0,0.769393,0.775369
3,0,11716,740.0,3.0,34171.0,990.94,10.0,51.0,21,0,7009,43533.0,0.0,0.0,0.716932,0.743981
4,0,9789,686.0,10.0,47003.0,503.71,16.7,25.0,13,1,16913,19553.0,1.0,0.0,0.769393,0.775369

In [7]:
data.isnull().sum()

Loan Status                     0
Current Loan Amount             0
Credit Score                    0
Years in current job            0
Annual Income                   0
Monthly Debt                    0
Years of Credit History         0
Months since last delinquent    0
Number of Open Accounts         0
Number of Credit Problems       0
Current Credit Balance          0
Maximum Open Credit             0
Bankruptcies                    0
Tax Liens                       0
Loan_status_home_ownership      0
purpose_term                    0
dtype: int64

In [8]:
import h2o
from h2o.estimators.gbm import H2OGradientBoostingEstimator
from h2o.estimators import H2OXGBoostEstimator
from h2o.estimators.deeplearning import H2ODeepLearningEstimator
from h2o.grid.grid_search import H2OGridSearch

In [9]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.20.1" 2023-08-24; OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04); OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
  Starting server from /home/shobot/PycharmProjects/environment/Loan Eligibility Prediction/lib/python3.10/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmp8jn2fciy
  JVM stdout: /tmp/tmp8jn2fciy/h2o_shobot_started_from_python.out
  JVM stderr: /tmp/tmp8jn2fciy/h2o_shobot_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------
H2O_cluster_uptime:         01 secs
H2O_cluster_timezone:       Asia/Kolkata
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.44.0.2
H2O_cluster_version_age:    19 days
H2O_cluster_name:           H2O_from_python_shobot_z69jev
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    7.689 Gb
H2O_cluster_total_cores:    16
H2O_cluster_allowed_cores:  16
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.10.12 final
--------------------------  -----------------------------

In [10]:
hf = h2o.H2OFrame(data)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [11]:
train, test = hf.split_frame(ratios = [.8], seed = 1234, )

In [12]:
gbm_params1 = {'learn_rate': [0.01, 0.1],
                'max_depth': [5, 9],
                'ntrees': [300, 500],
                'sample_rate': [0.8, 1.0],
                'col_sample_rate': [0.5, 1.0]}

In [13]:
gbm_grid1 = H2OGridSearch(model=H2OGradientBoostingEstimator,
                          grid_id='gbm_grid1',
                          hyper_params=gbm_params1)

In [ ]:
response=
gbm_grid1.train(x=predictors, y=response, training_frame=train, seed=1234)